### ISSUE TITLE
Dromoka's Command (Dragons of Tarkir) error.

### ISSUE THREAD

**Issue by BarbaAlGhul** [brine/mtg-octgn#120]
When I try to cast it from the hand, this error occurs:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ander\Documents\Octgn\GameDatabase\a6c8d2e8-7cd8-11dd-8f94-e62b56d89593\scripts\actions.py", line 343, in play
  File "C:\Users\ander\Documents\Octgn\GameDatabase\a6c8d2e8-7cd8-11dd-8f94-e62b56d89593\scripts\autoscript.py", line 314, in autoCast
  File "C:\Users\ander\Documents\Octgn\GameDatabase\a6c8d2e8-7cd8-11dd-8f94-e62b56d89593\scripts\autoscript.py", line 369, in initializeStackItem
  File "C:\Users\ander\Documents\Octgn\GameDatabase\a6c8d2e8-7cd8-11dd-8f94-e62b56d89593\scripts\autoscript.py", line 263, in tagConstructor
TypeError: unsupported operand type(s) for +=: 'dict' and 'NoneType'

result = play(Card(131109))

**Comment by brine** [comment]
i believe this is the same cause as #118
