### ISSUE TITLE
Attempting to cast "+2 Mace" from hand causes an autoscript error

### ISSUE THREAD

**Issue by omn1s** [brine/mtg-octgn#134]
Steps to reproduce: 
- Make a deck with "+2 Mace" as the only card.
- Launch a table and load the deck
- Draw the card
- Attempt to cast "+2 Mace" from your hand.

What happens:
- An autoscript error occurs:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\carrigan\AppData\Local\Programs\OCTGN\Data\GameDatabase\a6c8d2e8-7cd8-11dd-8f94-e62b56d89593\scripts\actions.py", line 457, in play
  File "C:\Users\carrigan\AppData\Local\Programs\OCTGN\Data\GameDatabase\a6c8d2e8-7cd8-11dd-8f94-e62b56d89593\scripts\autoscript.py", line 290, in autoCast
  File "C:\Users\carrigan\AppData\Local\Programs\OCTGN\Data\GameDatabase\a6c8d2e8-7cd8-11dd-8f94-e62b56d89593\scripts\autoscript.py", line 343, in initializeStackItem
  File "C:\Users\carrigan\AppData\Local\Programs\OCTGN\Data\GameDatabase\a6c8d2e8-7cd8-11dd-8f94-e62b56d89593\scripts\autoscript.py", line 186, in tagConstructor
  File "C:\Users\carrigan\AppData\Local\Programs\OCTGN\Data\GameDatabase\a6c8d2e8-7cd8-11dd-8f94-e62b56d89593\scripts\autoscript.py", line 72, in getTags
re.error: parsing "+2 Mace enters the battlefield" - Quantifier {x,y} following nothing.
result = play(Card(65538))

This issue can be worked around by just dragging the card out onto the table, also, the mace can still be tapped and interacted with once it is on the table.

**Comment by brine** [comment]
This will be closed now that the autoscript tags have been disabled
